### ISSUE TITLE
multiple consensus called when starting server

### ISSUE THREAD

**Issue by philip-zhan** [philip-zhan/decentralized-social-network#10]
Description:
Currently the server runs the consensus method multiple times which blocks the operation.
Need to solve this issue as well as allowing the server to get the longest valid blockchain data.

**Comment by zhoucong96** [comment]
1. Blocking(sync happens after the server is down): There is a duplicate in the code where the sync happens in both main method and the place before main method. The app.run() blocks the second sync due to this.

Solution:
Remove the duplicate, keep the main method.

2. Running two times: The flask automatically starts the server if it detects any change. This feature is implemented by spawning a child process so that the parent process is killed and the child process restart the server when there is a change. It is NOT a bug

Solution: 
(1) add an attribute use_reloader=False in the app.run(). However, when changes are made, the server will not restart itself
(2) Keep it as it is. It will not affect the server operation since they are different processes. Plus, it provides the restart feature

**Comment by philip-zhan** [comment]
good work!
